name: Auto-merge Exercism PRs

on:
  pull_request:
    types: [opened, synchronize, edited]

permissions:
  pull-requests: write
  contents: write

jobs:
  # This job will attempt to auto-merge the PR.
  automerge:
    # This job waits for the debug job to finish first.
    runs-on: ubuntu-latest
    # IMPORTANT: Update this username after you find the correct one from the 'debug' job logs.
    if: github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]'
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
